//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Comments = new HashSet<Comment>();
            this.DislikedFilms = new HashSet<DislikedFilm>();
            this.Film_to_Actor = new HashSet<Film_to_Actor>();
            this.Film_to_Country = new HashSet<Film_to_Country>();
            this.Film_to_Director = new HashSet<Film_to_Director>();
            this.Film_to_Genre = new HashSet<Film_to_Genre>();
            this.LikedFilms = new HashSet<LikedFilm>();
            this.SavedFilms = new HashSet<SavedFilm>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<decimal> IMDB { get; set; }
        public string Iframe { get; set; }
        public string Trailer { get; set; }
        public string Aboout { get; set; }
        public string Length { get; set; }
        public string Cover_Img { get; set; }
        public string Main_Img { get; set; }
        public string Iframe_Cover_Img { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> DublajID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Video_Img { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DislikedFilm> DislikedFilms { get; set; }
        public virtual Dublaj Dublaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film_to_Actor> Film_to_Actor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film_to_Country> Film_to_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film_to_Director> Film_to_Director { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film_to_Genre> Film_to_Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikedFilm> LikedFilms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedFilm> SavedFilms { get; set; }
    }
}
