//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_to_Country
    {
        public int ID { get; set; }
        public Nullable<int> FilmID { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Film Film { get; set; }
    }
}
